### ISSUE TITLE
Sending SMS fails when the SMS body has HTML special characters like &,<, >

### ISSUE THREAD

**Issue by thinkdj** [dash8x/dhiraagu-sms#1]
I am getting this error when sending a multi-line SMS 
**SMS was not sent. 401**
`Dash8x\DhiraaguSms\Exception\DhiraaguSmsException: SMS was not sent. 401: Error while parsing XML: The element type "COMMENT" must be terminated by the matching end-tag "</COMMENT>".`

**Comment by thinkdj** [comment]
This occurs when the BODY has `<>` in it. 
Eg of SMS content: `Use format: <ACTION> <ID> <COMMENT>`

**Comment by thinkdj** [comment]
It would be great to have urlencode() for 'body' internally in the SDK rather than depending on the input

**Comment by dash8x** [comment]
Fixed in v0.4.0
