### ISSUE TITLE
Endpoint URL updated by Dhiraagu

### ISSUE THREAD

**Issue by thinkdj** [dash8x/dhiraagu-sms#2]
SMS sending is failing as bulkmessage.dhiraagu.com.mv has been changed to bulksms.dhiraagu.com.mv.

**Comment by thinkdj** [comment]
Hi @dash8x Could you please update the package? We've been using this package since 2019 without any issues. Now Dhiraagu has changed the base URL and it's failing.

**Comment by thinkdj** [comment]
Okay, went through the package and `DhiraaguSms::class` and just realized that the URL can be overridden. That's awesome! Please feel free to close it if you're not planning on updating the default URL (But do update the readme mentioning the URL override, as it would be helpful for others)

**Comment by dash8x** [comment]
Thanks for pointing this out, I've updated the default URL in v0.4.0 and also updated the README
